// dashboard/parser.js
//
// Reads CareerPacer data files selected via a directory <input> and turns
// them into plain JS objects matching schema/1on1.schema.json and
// schema/idp-action.schema.json, so dashboard/index.html never has to deal
// with frontmatter/YAML directly.
//
// No build step: this is a plain script, meant to be loaded with a <script>
// tag alongside js-yaml from a CDN, e.g.:
//   <script src="https://cdn.jsdelivr.net/npm/js-yaml@4/dist/js-yaml.min.js"></script>
//   <script src="parser.js"></script>
//
// Data is loaded by fetching data/index.json (a flat manifest of relative
// paths, generated by scripts/generate-manifest.js) and then fetching each
// listed file. This requires the dashboard to be served over http(s) by a
// static server run from the repo root (e.g. `npx serve`) rather than
// opened directly via a file:// URL, since fetch() of local files is
// blocked by browsers under file://.
//
// Usage (from index.html):
//   const { oneOnOnes, idpActions, errors } = await CareerPacerParser.loadCareerPacerData();

(function (global) {
  'use strict';

  const FRONTMATTER_RE = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/;
  const DEFAULT_DATA_BASE_URL = '../data/';

  /**
   * Fetches a URL's contents as text, throwing a descriptive error on a
   * non-OK response.
   * @param {string} url
   * @returns {Promise<string>}
   */
  async function fetchText(url) {
    const res = await fetch(url);
    if (!res.ok) {
      throw new Error(`Failed to fetch ${url} (HTTP ${res.status})`);
    }
    return res.text();
  }

  /**
   * Splits raw Markdown-with-frontmatter text into the parsed YAML
   * frontmatter object and the remaining Markdown body.
   * @param {string} rawText
   * @returns {{ frontmatter: Object, body: string }}
   */
  function parseFrontmatter(rawText) {
    const match = FRONTMATTER_RE.exec(rawText);
    if (!match) {
      throw new Error('No YAML frontmatter block found (expected leading --- ... --- block)');
    }
    const [, yamlBlock, body] = match;
    const frontmatter = global.jsyaml.load(yamlBlock) || {};
    return { frontmatter, body: body.trim() };
  }

  /**
   * js-yaml parses unquoted YYYY-MM-DD scalars as JS Date objects (YAML
   * timestamp coercion). Normalize those back to plain "YYYY-MM-DD"
   * strings so date fields are always strings, matching the schemas.
   * @param {*} value
   * @returns {string|undefined}
   */
  function normalizeDate(value) {
    if (value instanceof Date) return value.toISOString().slice(0, 10);
    return value;
  }

  /**
   * Normalizes a data/1on1/*.md frontmatter object into a OneOnOne,
   * matching schema/1on1.schema.json.
   */
  function normalizeOneOnOne(frontmatter, body, relativePath) {
    return {
      id: frontmatter.id,
      date: normalizeDate(frontmatter.date),
      status: frontmatter.status,
      attendees: frontmatter.attendees || [],
      follow_ups: frontmatter.follow_ups || [],
      linked_actions: frontmatter.linked_actions || [],
      tags: frontmatter.tags || [],
      body,
      _file: relativePath,
    };
  }

  /**
   * Normalizes a data/idp/<year>.md frontmatter object (year + actions[])
   * into a flat array of IDPAction objects, matching the `idpAction`
   * definition in schema/idp-action.schema.json.
   */
  function normalizeIdpFile(frontmatter, body, relativePath) {
    const year = frontmatter.year;
    const actions = frontmatter.actions || [];
    return actions.map((action) => ({
      id: action.id,
      title: action.title,
      status: action.status,
      start_date: normalizeDate(action.start_date),
      target_date: normalizeDate(action.target_date),
      linked_evidence: action.linked_evidence || [],
      source: action.source,
      year,
      _file: relativePath,
    }));
  }

  /**
   * Fetches data/index.json, then fetches and parses every file it lists,
   * returning normalized OneOnOne and IDPAction objects. Files are sorted
   * into buckets by their relative-path prefix ("1on1/" or "idp/").
   * @param {string} [dataBaseUrl] Base URL to resolve manifest/file paths
   *   against, relative to the page loading this script. Defaults to
   *   "../data/", which matches dashboard/index.html being served from
   *   dashboard/ alongside a repo-root data/ folder.
   * @returns {Promise<{ oneOnOnes: Object[], idpActions: Object[], errors: Array<{ file: string, message: string }> }>}
   */
  async function loadCareerPacerData(dataBaseUrl) {
    const baseUrl = dataBaseUrl || DEFAULT_DATA_BASE_URL;
    const oneOnOnes = [];
    const idpActions = [];
    const errors = [];

    let relativePaths = [];
    try {
      const manifestText = await fetchText(`${baseUrl}index.json`);
      const manifest = JSON.parse(manifestText);
      relativePaths = Array.isArray(manifest.files) ? manifest.files : [];
    } catch (err) {
      errors.push({ file: 'data/index.json', message: err && err.message ? err.message : String(err) });
      return { oneOnOnes, idpActions, errors };
    }

    for (const relativePath of relativePaths) {
      try {
        const rawText = await fetchText(`${baseUrl}${relativePath}`);
        const { frontmatter, body } = parseFrontmatter(rawText);

        if (/(^|\/)1on1\//.test(relativePath)) {
          oneOnOnes.push(normalizeOneOnOne(frontmatter, body, relativePath));
        } else if (/(^|\/)idp\//.test(relativePath)) {
          idpActions.push(...normalizeIdpFile(frontmatter, body, relativePath));
        }
      } catch (err) {
        errors.push({ file: relativePath, message: err && err.message ? err.message : String(err) });
      }
    }

    return { oneOnOnes, idpActions, errors };
  }

  /**
   * Fetches and parses data/profile.json (name, role, company, manager,
   * team). Returns null if the file is missing or invalid, rather than
   * throwing, since the profile header is a lightweight nice-to-have.
   * @param {string} [dataBaseUrl]
   * @returns {Promise<Object|null>}
   */
  async function loadProfile(dataBaseUrl) {
    const baseUrl = dataBaseUrl || DEFAULT_DATA_BASE_URL;
    try {
      const text = await fetchText(`${baseUrl}profile.json`);
      return JSON.parse(text);
    } catch (err) {
      return null;
    }
  }

  global.CareerPacerParser = {
    parseFrontmatter,
    normalizeOneOnOne,
    normalizeIdpFile,
    loadCareerPacerData,
    loadProfile,
  };
})(typeof window !== 'undefined' ? window : globalThis);
